name: mental-health-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.19.0
      - pandas
      - numpy
      - scikit-learn
      - click==8.0.4  # Tambahkan ini untuk kompatibilitas