name: mental-health-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10  # ← Pastikan ini 3.10 atau 3.11
  - pip
  - pip:
      - mlflow==2.19.0
      - pandas
      - numpy
      - scikit-learn